version: '3.8'

services:
  hello-backend:
    image: hello-backend
    ports:
      - 8080:8080
    container_name: hello-backend
    environment:
      - REDIS_HOST=redis-cache

  hello-frontend:
    image: hello-frontend
    ports:
      - 5000:5000
    container_name: hello-frontend

  redis-cache:
    image: redis:7.2.1
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./cache:/data
    container_name: redis-cache
