version: "3.8"

services:
  hello-backend:
    image: hello-backend
    container_name: hello-backend
    environment:
      - REDIS_HOST=redis-cache
      - POSTGRES_HOST=hello-db
    depends_on:
      - redis-cache
      - db
    expose:
      - 8080

  hello-frontend:
    image: hello-frontend
    container_name: hello-frontend
    depends_on:
      - hello-backend
    expose:
      - 5000

  redis-cache:
    image: redis:7.2.1
    restart: unless-stopped
    volumes:
      - ./cache:/data
    container_name: redis-cache
    expose:
      - 6379

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: hello-db
    volumes:
      - ./database:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - hello-backend
      - hello-frontend
